title: 'KIN & COMPANY'
author:
  name: Kin
  email: joe@test.com
taxonomies:
  - category
  - tag
  - hierarchy
metadata:
  keywords: 'Kin & Company, Kin, Joe Vidich, Joseph Vidich, Kira Depaola, furniture, architecture, fabrication, brooklyn '
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
